wandb:
  group: Schwarzschild_geodesic_perihilion
  name: Schwarzschild_geodesics_perihilion
  project: GRNeF_Brandstetter_lab
  validate_every_n_epochs: 20
  validation_num_batches: 10
log_dir: /system/user/publicwork/crangano/neurips_runs/checkpoints/EinFields/schwarzschild/geodesic_perihilion
run_dir: /system/user/publicwork/crangano/neurips_runs/checkpoints/EinFields/schwarzschild/geodesic_perihilion/0iblhdd5
checkpoint:
  load_dir: ''
  reset_optimizer: false
data:
  data_dir: /system/user/publicwork/crangano/neurips_runs/neurips_data/EinFields/geodesic_perihilion/spherical/no_scale
  losses:
    hessian: false
    jacobian: true
architecture:
  activation: silu
  extra_model_args: {}
  hidden_dim: 128
  model_name: MLP
  num_layers: 6
  output_dim: 16
optimizer:
  extra_optimizer_args:
    b1: 0.95
    b2: 0.95
    eps: 1.0e-08
    precondition_frequency: 1
    weight_decay: 0.0
  extra_scheduler_args:
    alpha: 0.001
    decay_steps: 10000
    exponent: 1.0
  learning_rate: 0.001
  lr_scheduler: cosine_decay
  name: soap
training:
  epochs: 100
  gradient_conflict: grad_norm
  integration: false
  metric_type: distortion
  norm: mse
  num_batches: 100
  rng_seed: 0
